### ISSUE TITLE
Refresh rate switching while skipping

### ISSUE THREAD

**Issue by gurabli** [Raybuntu/LibreELEC.tv#14] opened 2017-07-18 04:26 UTC
Latest stable Krypton build, C2, I have Adjust refresh rate on Start/Stop ON and Sync Playback to Display ON, and when I play a video that is not 50fps like system settings, but 24fps, and I skip back or ff, the refresh rate switches to 50fps then back to 24fps on each skip step.

**Comment by Raybuntu** [comment] 2017-07-18 16:19
I can not reproduce the issue with my 60Hz Samsung TV

**Comment by gurabli** [comment] 2017-07-18 17:39
Do you have Adjust Refresh Rate on Start/Stop enabled? It happens to me all the time, if if set to Never, then works fine. Samsung plasma set to 50 Hz (because of Live TV, which is 50 Hz). Never seen this before, worked with wrxtasy version. What should I provide?

**Comment by Raybuntu** [comment] 2017-07-20 20:24
I will try to reproduce by setting my TV to 50Hz.
Not sure what might be the cause. Maybe @wrxtasy got a patch for that I don't know about.

**Comment by Memphiz** [comment] 2017-08-22 09:34
@gurabli does this fix youd issue:

echo 0 > /sys/class/tv/policy_fr_auto

**Comment by Raybuntu** [comment] 2017-09-29 06:52
I'm closing this because I can't reproduce it.

**Closed by Raybuntu** 2017-09-29 06:52 UTC
