### ISSUE TITLE
Leia build problem: pynacl

### ISSUE THREAD

**Issue by alorbach** [Raybuntu/LibreELEC.tv#28] opened 2017-10-06 13:14 UTC
Hi, 

I am trying to update my Leia build and it fails at pynacl since a few weeks. 
Do you have an idea? 

> BUILD    pynacl (target)
> Traceback (most recent call last):
>   File "setup.py", line 232, in <module>
>     "Programming Language :: Python :: 3.6",
>   File "/home/user/git/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/toolchain/lib/python2.7/distutils/core.py", line 111, in setup
>     _setup_distribution = dist = klass(attrs)
>   File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 319, in __init__
>   File "/home/user/git/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/toolchain/lib/python2.7/distutils/dist.py", line 287, in __init__
>     self.finalize_options()
>   File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 386, in finalize_options
>   File "/home/user/git/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/pynacl-1.1.2/.eggs/cffi-1.11.1-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 188, in cffi_modules
>     add_cffi_module(dist, cffi_module)
>   File "/home/user/git/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/pynacl-1.1.2/.eggs/cffi-1.11.1-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
>     execfile(build_file_name, mod_vars)
>   File "/home/user/git/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/pynacl-1.1.2/.eggs/cffi-1.11.1-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
>     exec(code, glob, glob)
>   File "src/bindings/build.py", line 32, in <module>
>     ffi = FFI()
>   File "/home/user/git/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/pynacl-1.1.2/.eggs/cffi-1.11.1-py2.7-linux-x86_64.egg/cffi/api.py", line 46, in __init__
>     import _cffi_backend as backend
> ImportError: /home/user/git/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/pynacl-1.1.2/.eggs/cffi-1.11.1-py2.7-linux-x86_64.egg/_cffi_backend.so: wrong ELF class: ELFCLASS32
> Makefile:12: recipe for target 'image' failed
> make: *** [image] Error 1
>

**Comment by Raybuntu** [comment] 2017-10-06 13:18
I haven't done a clean build yet. I'm going to investigate.

**Comment by Raybuntu** [comment] 2017-10-06 15:30
I can't reproduce. What makes me wonder is this:

`build.LibreELEC-Odroid_C2.arm-9.0-devel/pynacl-1.1.2/.eggs/`
I don't have that directory.

**Comment by alorbach** [comment] 2017-10-06 21:18
I have done a clean rebuild. Still breaks at the same position :( 
It's properly some cross compile issue as far as google results show

**Comment by alorbach** [comment] 2017-10-06 21:21
Are you using 32Bit or 64Bit Debian? 
I am on Debian9 64Bit

**Comment by Raybuntu** [comment] 2017-10-06 21:42
Looks like some cross compile issues but currently I don't see where the issue issue is. I'm on Debian Jessie 64bit.

For now here is a workaround:
Remove tuf from here:
https://github.com/Raybuntu/LibreELEC.tv/blob/Leia/packages/mediacenter/LibreELEC-settings/package.mk#L27
Tuf is currently not necessary and just for my development.

**Comment by alorbach** [comment] 2017-10-08 11:20
thanks, I could compile now proberly :)

**Comment by Raybuntu** [comment] 2017-10-08 17:33
@alorbach Are you able to build pynacl after a full build?

With:
... scripts/clean pynacl
... scripts/build pynacl

**Comment by pogo1975** [comment] 2017-10-08 18:02
after full build, error:

  BUILD    pynacl (target)
lto1: warning: switch -mcpu=cortex-a53 conflicts with -march=armv8-a switch
lto1: warning: switch -mcpu=cortex-a53 conflicts with -march=armv8-a switch
c/_cffi_backend.c: In function 'init_cffi_backend':
c/_cffi_backend.c:7401:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     Py_INCREF(&MiniBuffer_Type);
     ^~~~~~~~~

Installed /mnt/4TERA4/Leia9/build.LibreELEC-Odroid_C2.arm-9.0-devel/pynacl-1.1.2/.eggs/cffi-1.11.1-py2.7-linux-x86_64.egg
Searching for pycparser
Reading https://pypi.python.org/simple/pycparser/
Downloading https://pypi.python.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz#md5=72370da54358202a60130e223d488136
Best match: pycparser 2.18
Processing pycparser-2.18.tar.gz
Writing /tmp/easy_install-qLvlvE/pycparser-2.18/setup.cfg
Running pycparser-2.18/setup.py -q bdist_egg --dist-dir /tmp/easy_install-qLvlvE/pycparser-2.18/egg-dist-tmp-yrfaqP
warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
warning: no previously-included files matching 'lextab.*' found under directory 'tests'
warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
warning: no previously-included files matching 'lextab.*' found under directory 'examples'
zip_safe flag not set; analyzing archive contents...
pycparser.ply.lex: module references __file__
pycparser.ply.lex: module MAY be using inspect.getsourcefile
pycparser.ply.yacc: module references __file__
pycparser.ply.yacc: module MAY be using inspect.getsourcefile
pycparser.ply.yacc: module MAY be using inspect.stack
pycparser.ply.ygen: module references __file__
creating /mnt/4TERA4/Leia9/build.LibreELEC-Odroid_C2.arm-9.0-devel/pynacl-1.1.2/.eggs/pycparser-2.18-py2.7.egg
Extracting pycparser-2.18-py2.7.egg to /mnt/4TERA4/Leia9/build.LibreELEC-Odroid_C2.arm-9.0-devel/pynacl-1.1.2/.eggs

Installed /mnt/4TERA4/Leia9/build.LibreELEC-Odroid_C2.arm-9.0-devel/pynacl-1.1.2/.eggs/pycparser-2.18-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 232, in <module>
    "Programming Language :: Python :: 3.6",
  File "/mnt/4TERA4/Leia9/build.LibreELEC-Odroid_C2.arm-9.0-devel/toolchain/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 319, in __init__
  File "/mnt/4TERA4/Leia9/build.LibreELEC-Odroid_C2.arm-9.0-devel/toolchain/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 386, in finalize_options
  File "/mnt/4TERA4/Leia9/build.LibreELEC-Odroid_C2.arm-9.0-devel/pynacl-1.1.2/.eggs/cffi-1.11.1-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 188, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/mnt/4TERA4/Leia9/build.LibreELEC-Odroid_C2.arm-9.0-devel/pynacl-1.1.2/.eggs/cffi-1.11.1-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/mnt/4TERA4/Leia9/build.LibreELEC-Odroid_C2.arm-9.0-devel/pynacl-1.1.2/.eggs/cffi-1.11.1-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
    exec(code, glob, glob)
  File "src/bindings/build.py", line 32, in <module>
    ffi = FFI()
  File "/mnt/4TERA4/Leia9/build.LibreELEC-Odroid_C2.arm-9.0-devel/pynacl-1.1.2/.eggs/cffi-1.11.1-py2.7-linux-x86_64.egg/cffi/api.py", line 46, in __init__
    import _cffi_backend as backend
ImportError: /mnt/4TERA4/Leia9/build.LibreELEC-Odroid_C2.arm-9.0-devel/pynacl-1.1.2/.eggs/cffi-1.11.1-py2.7-linux-x86_64.egg/_cffi_backend.so: wrong ELF class: ELFCLASS32

**Comment by Raybuntu** [comment] 2017-10-09 09:21
Fixed in https://github.com/Raybuntu/LibreELEC.tv/commit/1a9b6c59599254d46847b56861d430416030eb2c

**Closed by Raybuntu** 2017-10-09 09:21 UTC
